from typing import Any, Protocol

class _StyleContext(Protocol):
    def add_class(self, css_class: str) -> None: ...

class _GtkWindow(Protocol):
    def set_decorated(self, decorated: bool) -> None: ...
    def set_resizable(self, resizable: bool) -> None: ...
    def set_opacity(self, opacity: float) -> None: ...
    def set_keep_above(self, setting: bool) -> None: ...
    def set_accept_focus(self, setting: bool) -> None: ...
    def set_focus_on_map(self, setting: bool) -> None: ...
    def set_can_focus(self, setting: bool) -> None: ...
    def set_focusable(self, setting: bool) -> None: ...
    def set_skip_taskbar_hint(self, setting: bool) -> None: ...
    def set_skip_pager_hint(self, setting: bool) -> None: ...
    def set_type_hint(self, hint: int) -> None: ...
    def set_default_size(self, width: int, height: int) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def add_events(self, events: int) -> None: ...
    def connect(self, detailed_signal: str, handler: Any, *args: Any) -> None: ...
    def add_controller(self, controller: Any) -> None: ...
    def add(self, widget: Any) -> None: ...
    def show_all(self) -> None: ...
    def set_child(self, widget: Any) -> None: ...
    def present(self) -> None: ...
    def destroy(self) -> None: ...

class _GtkBox(Protocol):
    def set_margin_top(self, margin: int) -> None: ...
    def set_margin_bottom(self, margin: int) -> None: ...
    def set_margin_start(self, margin: int) -> None: ...
    def set_margin_end(self, margin: int) -> None: ...
    def set_hexpand(self, hexpand: bool) -> None: ...
    def set_halign(self, align: int) -> None: ...
    def pack_start(
        self, child: Any, expand: bool, fill: bool, padding: int
    ) -> None: ...
    def append(self, child: Any) -> None: ...

class _GtkLabel(Protocol):
    def set_xalign(self, xalign: float) -> None: ...
    def set_halign(self, align: int) -> None: ...
    def get_style_context(self) -> _StyleContext: ...
    def set_markup(self, markup: str) -> None: ...
    def set_justify(self, justify: int) -> None: ...
    def set_line_wrap(self, setting: bool) -> None: ...
    def set_wrap(self, setting: bool) -> None: ...
    def set_max_width_chars(self, chars: int) -> None: ...

class _GtkButton(Protocol):
    def connect(self, detailed_signal: str, handler: Any, *args: Any) -> None: ...

class _GtkWindowType:
    POPUP: int

class _GtkOrientation:
    VERTICAL: int
    HORIZONTAL: int

class _GestureClick(Protocol):
    def set_button(self, button: int) -> None: ...
    def connect(self, detailed_signal: str, handler: Any, *args: Any) -> None: ...

class _GtkAlign:
    CENTER: int
    FILL: int

class _GtkJustification:
    CENTER: int

class _GtkNamespace(Protocol):
    WindowType: type[_GtkWindowType]
    Orientation: type[_GtkOrientation]
    Align: type[_GtkAlign]
    Justification: type[_GtkJustification]
    GestureClick: type[_GestureClick]

    def Window(self, *, type: int | None = None) -> _GtkWindow: ...
    def Box(self, *, orientation: int, spacing: int = 0) -> _GtkBox: ...
    def Label(self, *, label: str = "") -> _GtkLabel: ...
    def Button(self, *, label: str = "") -> _GtkButton: ...
    def main(self) -> None: ...

class _GdkWindowTypeHint:
    NOTIFICATION: int

class _GdkEventMask:
    BUTTON_PRESS_MASK: int

class _Geometry(Protocol):
    x: int
    y: int
    width: int
    height: int

class _GdkMonitor(Protocol):
    def get_geometry(self) -> _Geometry: ...

class _GListModel(Protocol):
    def get_n_items(self) -> int: ...
    def get_item(self, index: int) -> _GdkMonitor | None: ...

class _GdkDisplay(Protocol):
    def get_primary_monitor(self) -> _GdkMonitor | None: ...
    def get_monitors(self) -> _GListModel: ...
    def get_n_monitors(self) -> int: ...
    def get_monitor(self, index: int) -> _GdkMonitor | None: ...

class _GdkDisplayFactory(Protocol):
    def get_default(self) -> _GdkDisplay | None: ...

class _GdkNamespace(Protocol):
    Display: _GdkDisplayFactory
    WindowTypeHint: type[_GdkWindowTypeHint]
    EventMask: type[_GdkEventMask]

class _MainLoop(Protocol):
    def run(self) -> None: ...

class _GLibNamespace(Protocol):
    def MainLoop(self) -> _MainLoop: ...
    def idle_add(self, callback: Any, *args: Any) -> int: ...
    def timeout_add(self, interval: int, callback: Any, *args: Any) -> int: ...
    def source_remove(self, source_id: int) -> bool: ...
    def markup_escape_text(self, text: str) -> str: ...

class _Layer:
    TOP: int

class _Edge:
    TOP: int
    BOTTOM: int
    LEFT: int
    RIGHT: int

class _KeyboardMode:
    NONE: int

class _GtkLayerShellNamespace(Protocol):
    Layer: type[_Layer]
    Edge: type[_Edge]
    KeyboardMode: type[_KeyboardMode]

    def init_for_window(self, window: _GtkWindow) -> None: ...
    def set_layer(self, window: _GtkWindow, layer: int) -> None: ...
    def set_monitor(self, window: _GtkWindow, monitor: _GdkMonitor) -> None: ...
    def set_anchor(
        self, window: _GtkWindow, edge: int, anchor_to_edge: bool
    ) -> None: ...
    def set_margin(self, window: _GtkWindow, edge: int, margin: int) -> None: ...
    def set_keyboard_mode(self, window: _GtkWindow, mode: int) -> None: ...
    def set_exclusive_zone(self, window: _GtkWindow, zone: int) -> None: ...

Gtk: _GtkNamespace
Gdk: _GdkNamespace
GLib: _GLibNamespace
GtkLayerShell: _GtkLayerShellNamespace
Gtk4LayerShell: _GtkLayerShellNamespace
